### ISSUE TITLE
Navbar.js su 2 piani

### ISSUE THREAD

**Issue by SL-Rad** [SL-Rad/SL-Rad-Vademecum#138]
Possiamo dividere la navbar sistematicamente a due colonne sui PC?

Home | RX | Eco | TC | RM | Contrast | 
PS | [...] | Telefoni

**Comment by Giux2** [comment]
Quando dici "due colonne" intendi due righe orizzontali ? Una sopra e l'altra sotto? Come fossero due menù?

**Comment by GeorgeCeladon** [comment]
Si due righe hai ragione

**Comment by Giux2** [comment]
> Si due righe hai ragione

Ok, potrebbero essere due menu js separati, uno alto più grande e uno basso leggermente più piccolo. ti aggiorno

**Comment by Giux2** [comment]
@GeorgeCeladon ho ampliato la larghezza del contenitore "main" in questo modo il menu è quasi tutto gestibile su una sola riga. vedi https://sl-rad.github.io/SL-Rad-Vademecum/test/radiologia_tradizionale.html
