### ISSUE TITLE
2021065646 - TC TBC cavitaria e miliare

### ISSUE THREAD

**Issue by GeorgeCeladon** [SL-Rad/SL-Rad-Vademecum#15]

**Comment by SL-Rad** [comment]
![image](https://user-images.githubusercontent.com/85334987/142466876-511ac5f3-faf0-459f-9117-3e5430e1c29f.png)
![image](https://user-images.githubusercontent.com/85334987/142466911-6dbc1a36-27fe-4174-9e6f-8fdbfc86d4bb.png)



Strie dense di aspetto fibro-disventilativo a sede intercleidoilare destra e sfumati addensamenti parenchimali al campo medio-superiore di sinistra da correlare clinicamente (in relazione a fenomeni flogistici? altro?).
Opacità tondeggianti di dimensioni subcentimetriche all'emitorace di sinistra, necessarie di confronto con indagini precedenti.
Ipodiafania a sede apicale bilaterale come per la presenza di versamento pleurico in tali sedi.
Limitate immagini compatibili con camere pleuriche proiettivamente a carico del campo superiore di sinistra in proiezione PA e in regione anteriore in LL.
L'ombra cardiaca di dimensioni nei limiti di normalità.
Trrachea in asse.

---

![image](https://user-images.githubusercontent.com/85334987/142466364-70283647-de40-4b98-a1fb-d9761c84ee1b.png)
![image](https://user-images.githubusercontent.com/85334987/142466390-53dbe544-8143-4a07-bb70-3fa38516e4cf.png)
![image](https://user-images.githubusercontent.com/85334987/142466479-2ce3e532-513a-4704-a038-537fcb81ee64.png)
![image](https://user-images.githubusercontent.com/85334987/142466570-56455d15-f55b-4d8b-b98d-799e1cdffef9.png)
![image](https://user-images.githubusercontent.com/85334987/142466624-b867e6a2-316c-4d92-a283-44d0582fb631.png)
![image](https://user-images.githubusercontent.com/85334987/142466673-8a9f86c3-3dff-47fc-b348-10cc15510813.png)

Esame eseguito in regime di DEA nelle sole condizioni basali con quesito diagnostico: "emoftoe in fumatore, eseguita Rx torace: addensamenti tondeggianti emitorace sx, agli ee Gb 12.00 e pcr 4".

Sono rilevabili multiple lesioni cavitate, del diametro variabile da pochi millimetri a 60 mm, maggiormente estese ai lobi superiori in associazione a numerose bronchiectasie e fenomeni di retrazione parenchimale 

A livello del lobo medio e inferiore di sinistra tali lesioni presentano pareti ispessite e materiale ipodenso contenuto nella regione cavitaria.

Concomitano aree di micronodulia, per lo più a carico del lobo superiore destro, del lobo medio e del lobo inferiore sinistro.

Tali reperti risultano meritevoli di correlazione clinico-laboratoristica ed approfondimento (fenomeni flogistici da micobatteriosi? sovrainfezione micotica?). 

Non si osservano falde di versamento pleurico né versamento pericardico. 

La trachea e i grossi bronchi sono pervi. 

Nelle scansioni addominali comprese in esame si osservano espansi surrenbalici bilaterali (diam 19 mm al corpo del surrene dx e 22 mm all'aletta mediale del surrene sinistro), a densità perlopiù inferiore a 10 HU, compatibili in prima ipotesi con adenomi.
