### ISSUE TITLE
2021065627 - ECO AI | K Ovarico?

### ISSUE THREAD

**Issue by GeorgeCeladon** [SL-Rad/SL-Rad-Vademecum#16]

**Comment by SL-Rad** [comment]
![image](https://user-images.githubusercontent.com/85334987/142458627-f7f2fb74-c2ef-4dfb-a110-f88769fb6531.png)
![image](https://user-images.githubusercontent.com/85334987/142458691-45bb12d0-8cca-4452-b0fa-c851462a2fcc.png)
![image](https://user-images.githubusercontent.com/85334987/142458757-35278ea0-ad83-4558-abb4-ba729b156d3f.png)

Esame eseguito in regime di urgenza con quesito diagnostico 
"metrorragia in pz in nao, dolore addominale nei quadranti inferiori: lesioni uterine? fibromi?"

Rilevabile in ipogastrio una voluminosa formazione espansiva (9 x 11 cm) a struttura disomogena prevalentemente ipoecogena con contestuali limitate aree anecogene di aspetto cistitico caratterizzata al controllo ECD da modesto segnale vascolare. (formazione espansiva ad origine annessiale?)
Lesione a sviluppo in stretto rapporto con il fondo uterino.
Utero antiverso di regolare dimensioni in relazione all'età della paziente.
Posteriormente rilevabile possibile ulteriore formazione disomogenea con limitate areole cistiche nel contesto, di 5 cm circa. 
Vescica, scarsamente repleta, a pareti ben distensibili e contenuto anecogeno omogeneo.
Non falde di versamento fluido nello scavo pelvico.
