### ISSUE TITLE
2020060002 - Rettografia | Diverticoli

### ISSUE THREAD

**Issue by AnonimoFiorentino** [SL-Rad/SL-Rad-Vademecum#19]

**Comment by SL-Rad** [comment]
![image](https://user-images.githubusercontent.com/85334987/143228319-e6cdc3b9-6a10-4f64-aa2d-2a6026903610.png)
![image](https://user-images.githubusercontent.com/85334987/143228364-08cedc77-291f-433d-9a03-6caddf8a88a3.png)
![image](https://user-images.githubusercontent.com/85334987/143228407-a4ea0bba-1928-411b-bfb6-c65b6389a7b5.png)
![image](https://user-images.githubusercontent.com/85334987/143228513-2b4b89a4-599b-4c12-83c6-9db72d54a9bf.png)




**Quesito clinico:** Paziente in **esiti di RAR** e **confezionamento di ileostomia di protezione in fianco destro**. 
Richiesto Rx transito in **previsione di intervento chirurgico di chiusura di ileostomia**.

**Tecnica d'esame:** sono stati acquisiti radiogrammi prima e dopo cateterizzazione del lume ileale nella sua porzione efferente tramite **catetere di Foley 14 Ch** e **somministrazione di circa 100 ml di MdC idrosolubile (Gastrografin)**. 
A completamento diagnostico sono stati **iniettati ulteriori 100 cc di MdC direttamente in ampolla rettale tramite sondino endorettale**.

**Riscontri radiologici:** il MdC procede regolarmente attraverso l'ansa efferente,oltrepassando la valvola ileocecale e opacizzando omogeneamente il colon. 
Si osserva **marcato e diffuso quadro di diverticolosi del grosso intestino**, prevalente a livello del **colon discendente**, fino in regione pre-anastomotica. 
Proprio a livello dell'**anostomosi colo-rettale T-T** si osserva opacizzazione di una **formazione peduncolata, che rimane stabile per forma e dimensioni al variare dei decubiti** e anche dopo ulteriore somministrazione di MdC tramite sondino endorettale. 
Nel complesso il reperto è di dubbia interpretazione, anche se riferibile **in prima ipotesi a ulteriore formazione diverticolare del tratto di colon pre-anastomotico** piuttosto che a spandimento extraluminale di mdc a fondo cieco. 
Non si osservano significativi spandimenti extraluminali di MdC nè tratti stenotici. 

A valle dell'anastomosi il MdC procede opacizzando l'ampolla rettale. 

**Conclusioni:** regolare transito del MdC attraverso l'anostomosi colo-rettale in **assenza di sicuri spandimenti extraluminali** di MdC o significativi tratti stenotici. Concomita **marcato quadro di diverticolosi del grosso intestino**.
