### ISSUE TITLE
Cisto correzione vademecum

### ISSUE THREAD

**Issue by AnonimoFiorentino** [SL-Rad/SL-Rad-Vademecum#23]
Aggiungere su Cisto che il Valsalva va fatto a pancja in giù

**Comment by SL-Rad** [comment]
👍

**Comment by SL-Rad** [comment]
@AnonimoFiorentino 
Credo di averlo già corretto, nel caso se rivedi che manca allega il link alla pagina dove manca.
Per adesso chiudo la issue.
