### ISSUE TITLE
Aggiungere Numeri Onco ambulatoriali

### ISSUE THREAD

**Issue by minnesota-11** [SL-Rad/SL-Rad-Vademecum#24]
Nei media del gruppo rls grandi successi

**Comment by SL-Rad** [comment]
Ottimo, ci attiviamo!
Grazie

**Comment by SL-Rad** [comment]
![image](https://user-images.githubusercontent.com/85334987/142079226-59e4f228-32c3-4c5b-8af2-7d075602d08f.png)
