### ISSUE TITLE
Seconda revisione - Gestione Agenda TC

### ISSUE THREAD

**Issue by GeorgeCeladon** [SL-Rad/SL-Rad-Vademecum#25]
Servirebbe una seconda revisione della nuova sezione "gestione agenda" inserita nella pagina della tomografia computerizzata. 

Il documento è stato già trascritto in maniera formale e anonimizzato ma va visto se può essere reso meglio a livello di editing.

@bayernk

**Comment by SL-Rad** [comment]
- [ ] slot ambulatoriali
- [ ] slot ricoverati
- [ ] slot pre-ricovero
- [ ] slot cardio-tc
- [ ] slot colonscopie virtuali
- [ ] esami ultraspecialistici
- [ ] attività aggiuntiva
- [ ] slot covid
- [ ] esame da non prenotare
