### ISSUE TITLE
2021067806 -  TC | Arteria lusoria

### ISSUE THREAD

**Issue by minnesota-11** [SL-Rad/SL-Rad-Vademecum#33]
Variante anatomica ben visibile alla tc 202167806
Da segnalare perché può causare - disfagia 
@GeorgeCeladon

**Comment by SL-Rad** [comment]
![image](https://user-images.githubusercontent.com/85334987/143223842-62abf223-ac86-40f3-851f-32987d16494e.png)

![image](https://user-images.githubusercontent.com/85334987/143224215-3b1a316f-4842-4651-b8b8-0321c95179ea.png)

![image](https://user-images.githubusercontent.com/85334987/143225076-f2ae0d17-1a9b-4ba3-9d70-43c90f0fe511.png)


_"Concomita, quale variante anatomica, arteria lusoria e di diffusa ateromasia calcifica a carico dei bulbi carotidei e dell'origine della a. carotide interna."_

La **ARSA** (arteria succlavia destra aberrante o arteria lusoria) è la più comune anomalia congenita dell'arco aortico, con un’incidenza riportata in letteratura dello 0.5-2%.

**L’arteria succlavia di destra**, invece di originare dal tronco brachiocefalico (o anonimo destro)  insieme  alla  carotide  di  destra,  **origina  separatamente  a  livello  della  porzione  più  distale dell'arco aortico**, dopo l’origine della succlavia di sinistra.

**Bibliografia**
[ARSA (arteria succlavia destra aberrante o arteria lusoria)](https://www.ospedale.al.it/wp-content/uploads/2016/11/ARSA.pdf)
[ Dysphagia lusoria: a comprehensive review ](https://pubmed.ncbi.nlm.nih.gov/17958718/)
