### ISSUE TITLE
2021068474 - RX Torace | Emopoiesi extramodollare costale

### ISSUE THREAD

**Issue by AnonimoFiorentino** [SL-Rad/SL-Rad-Vademecum#36]

**Comment by SL-Rad** [comment]
@AnonimoFiorentino

**Comment by SL-Rad** [comment]
![image](https://user-images.githubusercontent.com/85334987/143226221-d938427b-0f83-4fac-a4dc-c92979ddd4fd.png)

Tenuto conto della diversa tecnica di esecuzione dei radiogrammi, rispetto ad un precedente controllo, con i limiti imposti dal **noto quadro di interessamento costale** da **eritropoiesi extramidollare**, non documentabili grossolane lesioni acute a focolaio né falde di versamento pleurico ad entrambi gli ambiti polmonari.

**Bibliografia**
[Thoracic extramedullary hematopoiesis in sickle-cell disease](https://www.ajronline.org/doi/pdf/10.2214/ajr.149.5.889)
