### ISSUE TITLE
2021068566 - ECO SPALLA INFILTRAZIONI

### ISSUE THREAD

**Issue by GeorgeCeladon** [SL-Rad/SL-Rad-Vademecum#38]

**Comment by SL-Rad** [comment]
QD: "CONFLITTO ACROMION-CLAVICOLA"

**GUIDA ECO INF. SPALLA**
All'indagine odierna si rileva **lesione a tutto spessore del tendine sovraspinato**, con **ampia comunicazione fra cavità articolare e borsa subacromion-deltoidea**, distesa, con segni di sinovite periferica. 

Sotto guida ecografica, mediante ago 21 G. è stato **effettuato drenaggio di circa 15 mL di fluido siero sinoviale**. 
Al termine procedura è stata effettuata **infiltrazione tramite medesimo ago di 2 mm in metilprednisolone acetato** e proprie placche né a scopo antiflogistico e anestetico. 
Non si rilevano complicanze ecografiche precoci.
