### ISSUE TITLE
2021068567 - ECO MSK | Fascite plantare

### ISSUE THREAD

**Issue by GeorgeCeladon** [SL-Rad/SL-Rad-Vademecum#39]

**Comment by SL-Rad** [comment]
Indagine effettuata a livello della fascia plantare bilateralmente. 
Non si rilevano alterazioni di o ecostruttura delle stesse.
Non sono evidenziabili alterazioni di aspetto calcifico. 
Regolare il tessuto superficiale e profondo. 
Non si rilevano alterazioni del tendine di Achille o del tessuto adiposo del triangolo di Kager.
