### ISSUE TITLE
Atlas RX orthopedic devices

### ISSUE THREAD

**Issue by AnonimoFiorentino** [SL-Rad/SL-Rad-Vademecum#44]
https://pubs.rsna.org/doi/10.1148/rg.253055010

**Comment by SL-Rad** [comment]
Caricato in bibliografia di radiologia tradizionale e in linlk utili

https://sl-rad.github.io/SL-Rad-Vademecum/radiologia_tradizionale.html
https://sl-rad.github.io/SL-Rad-Vademecum/risorse_utili.html

**Comment by AnonimoFiorentino** [comment]
> Caricato in bibliografia di radiologia tradizionale e in linlk utili
> 
> https://sl-rad.github.io/SL-Rad-Vademecum/radiologia_tradizionale.html
> https://sl-rad.github.io/SL-Rad-Vademecum/risorse_utili.html

Non sarebbe meglio mettere il link all'articolo sul sito (che tanto è open access) rispetto a far scaricare il PDF?
