### ISSUE TITLE
2021071495 | Rx - Fibrotorace NDD

### ISSUE THREAD

**Issue by AnonimoFiorentino** [SL-Rad/SL-Rad-Vademecum#78]
![image](https://user-images.githubusercontent.com/94114070/144625649-049f13d5-2b71-4cd4-966a-02b96eb93471.png)
![image](https://user-images.githubusercontent.com/94114070/144625694-8236d492-327e-4acc-ad22-2757d239b7b0.png)

_Marcata **perdita di volume dell'emitorace** destro, associata a **retrazione del parenchima** omolaterale e diffusa **ipodiafania di fondo** in verosimile **quadro di fibrotorace** (ove non sono escludibili manifestazioni flogistico-disventilativa del parenchima). 
**Ispessimento delle superfici pleuriche** apico-parieto-basali, con possibile impegno fluido nel seno costofrenico. 
Consensuale **shift delle strutture mediastiniche** verso destra. 
Indispensabile confronto con RX/TC precedenti, correlazione clinico-anamnestica ed eventuale approfondimento con metodica di II livello (TC). 
Non evidenziabili alterazioni acute "a focolaio" né falde di versamento pleurico a carico dell'emitorace sinistro. 
Manifestazioni degenerative croniche del rachide dorsale caratterizzate da riduzione di ampiezza degli spazi intersomatici e diffusi fenomeni osteofitari._

**Comment by GeorgeCeladon** [comment]
Il **fibrotorace** è definito come una **fibrosi all'interno dello spazio pleurico** ed è talvolta definita come **"buccia pleurica (pleural peel)**". 
Si verifica secondariamente a una risposta infiammatoria a uno dei seguenti eventi:
- tubercolosi / pleurite tubercolosa / empiema tubercoloso 
  - principalmente come sequela tardiva
- empiema toracico
- malattia pleurica legata all'amianto
- artrite reumatoide
- emotorace
- malattia del tessuto connettivo
- lupus eritematoso sistemico
- uremia
- reazioni ai farmaci
- pleurodesi terapeutica

Il fibrotorace è caratterizzato da un ispessimento pleurico relativamente liscio che talvolta può anche essere **calcifico**. 
La pleura mediastinica è solitamente risparmiata.
Si associa a **marcata perdita di volume dell'emitorace interessato.**


[Radiopaedia - Fibrothorax](https://radiopaedia.org/articles/fibrothorax)

---

![image](https://user-images.githubusercontent.com/64736051/144689943-a56bd21e-56ad-47bb-afb5-4acb67cfda71.png)

Chest radiography, showing bilateral calcified pleural plaques, right greater than left.

[American Journal of Respiratory and Critical Care Medicine - Extensive Calcified Fibrothorax](https://www.atsjournals.org/doi/10.1164/rccm.201606-1265IM)
