### ISSUE TITLE
2021071820 | RX - ricostruzione rotula secondo Hauban

### ISSUE THREAD

**Issue by AnonimoFiorentino** [SL-Rad/SL-Rad-Vademecum#79]
Prima
![image](https://user-images.githubusercontent.com/94114070/144624960-d59521c3-d035-4914-9f43-04ac56cbfa3c.png)

Dopo
![image](https://user-images.githubusercontent.com/94114070/144625167-6cbe924e-f48b-4ebe-9aeb-24f5833b98ed.png)
![image](https://user-images.githubusercontent.com/94114070/144625213-fc7daf5e-ae94-48e9-8006-9e622a36108c.png)

_Esame eseguito dopo ricostruzione rotulea secondo Hauban.
In esiti di frattura trasversa completa della rotula intervento chirurgico si riconosce buon allineamento delle componenti ossee.
Persiste linea di radiotrasparenaza. Enfisema sottocutaneo e clips chirurgiche nei tessuti molli contigui al sito d'intervento._

**Comment by GeorgeCeladon** [comment]
## BIBLIOGRAFIA
- [Fractures de la rotule (francese)](https://www.slideserve.com/embed/1208054)
![CopyQ LGJpJW](https://user-images.githubusercontent.com/64736051/144689160-77467f66-e6ca-47c4-9aba-953bc3331700.png)
![CopyQ jOiJEF](https://user-images.githubusercontent.com/64736051/144689170-9095f066-db2b-4bb5-b33d-00556eb3b756.png)
![CopyQ hySadW](https://user-images.githubusercontent.com/64736051/144689172-268946c0-4ff2-47e2-b0ff-92e6204dd447.png)
![CopyQ EExjvh](https://user-images.githubusercontent.com/64736051/144689234-fcec52a1-0654-4fc8-9639-cdb87210936a.png)
![CopyQ PdbCyU](https://user-images.githubusercontent.com/64736051/144689246-ad568a14-f259-4aff-8182-dd2639d91837.png)

- [Slide instabilità di rotula - fratture e fisoterapia](http://www.fisiokinesiterapia.biz/NewDownload/rotula2.pdf)
![image](https://user-images.githubusercontent.com/64736051/144689445-c19b3a36-a0fa-47bd-b595-2fd23169621b.png)
