### ISSUE TITLE
Risorsa per capire che fanno Ortopedici (?)

### ISSUE THREAD

**Issue by AnonimoFiorentino** [SL-Rad/SL-Rad-Vademecum#80]
https://surgeryreference.aofoundation.org/

È possibile selezionare il segmento coinvolto, il tipo di frattura e che intervento è stato fatto, con anche i correlati radiologici

**Comment by GeorgeCeladon** [comment]
Veramente fico! 
Per ora lo metto tra i link utili ma magari poi pensiamo ad un modo furbo di implementarlo in RX
